(rule
  (targets parser.cmly parser.ml parser.mli)
  (deps parser.mly)
  (action (run menhir --table --cmly --lalr parser.mly)))

(rule
 (alias fuzz-regressions)
 (deps parser.cmly state.dat)
 (targets state_new.dat report_new.md regressions_report.md)
 (action
  (run
   %{bin:ocamlgrammarfuzzer}
   --ocamlformat-check
   --cmly
   parser.cmly
   --entrypoint
   implementation
   --entrypoint
   interface
   --exhaust
   --comments
   --ocamlformat
   %{exe:../../bin/ocamlformat/main.exe}
   --regressions-not-fatal
   --track-regressions-from
   state.dat
   --track-regressions-to
   state_new.dat
   --save-report-to
   report_new.md
   --regressions-report-to
   regressions_report.md))
  (mode (promote (only regressions_report.md))))

(rule
 (alias fuzzer)
 (action
  (cmp state.dat state_new.dat)))

(rule
 (alias fuzzer-report)
 (action
  (diff report.md report_new.md)))
