(rule
 (enabled_if %{env:WITH_FUZZER=false})
 (targets parser.cmly parser.ml parser.mli)
 (deps parser.mly)
 (action
  (run menhir --unused-tokens --table --cmly --lalr parser.mly)))

(rule
 (enabled_if %{env:WITH_FUZZER=false})
 (deps parser.cmly state.dat)
 (targets state_new.dat report.md regressions_report.md)
 (action
  (run
   %{bin:ocamlgrammarfuzzer}
   --ocamlformat-check
   --cmly
   parser.cmly
   --entrypoint
   implementation
   --entrypoint
   interface
   --exhaust
   --comments
   --ocamlformat
   %{exe:../../bin/ocamlformat/main.exe}
   --regressions-not-fatal
   --track-regressions-from
   state.dat
   --track-regressions-to
   state_new.dat
   --save-report-to
   report.md
   --regressions-report-to
   regressions_report.md)))

(rule
 (enabled_if %{env:WITH_FUZZER=false})
 (alias fuzzer)
 (action
  (progn
   (run sh -c "echo Check:")
   (run sh -c "echo '- '$PWD'/%{dep:report.md} for all errors'")
   (run
    sh
    -c
    "if test -s %{dep:regressions_report.md}; then echo '- '$PWD'/%{dep:regressions_report.md} for regressions'; fi"))))

(rule
 (enabled_if %{env:WITH_FUZZER=false})
 (alias fuzzer-no-regression)
 (action
  (run test ! -s %{dep:regressions_report.md})))

(rule
 (enabled_if %{env:WITH_FUZZER=false})
 (alias fuzzer-update-state)
 (action
  (cmp state.dat state_new.dat)))
